Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from shexviz import shex2dot
f = open("cotton/productionShape.shex", "r")
shex = f.read()

shex2dot.shex2dot(shex, "test").view()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [0;32m~/.local/lib/python3.10/site-packages/shexviz/__init__.py:4[0m
[1;32m      3[0m [38;5;28;01mtry[39;00m:
[0;32m----> 4[0m     [38;5;28;01mimport[39;00m [38;5;21;01mtomllib[39;00m
[1;32m      5[0m [38;5;28;01mexcept[39;00m [38;5;167;01mModuleNotFoundError[39;00m:

[0;31mModuleNotFoundError[0m: No module named 'tomllib'

During handling of the above exception, another exception occurred:

[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mshexviz[39;00m [38;5;28;01mimport[39;00m shex2dot
[1;32m      2[0m f [38;5;241m=[39m [38;5;28mopen[39m([38;5;124m"[39m[38;5;124mcotton/productionShape.shex[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mr[39m[38;5;124m"[39m)
[1;32m      3[0m shex [38;5;241m=[39m f[38;5;241m.[39mread()

File [0;32m~/.local/lib/python3.10/site-packages/shexviz/__init__.py:6[0m
[1;32m      4[0m     [38;5;28;01mimport[39;00m [38;5;21;01mtomllib[39;00m
[1;32m      5[0m [38;5;28;01mexcept[39;00m [38;5;167;01mModuleNotFoundError[39;00m:
[0;32m----> 6[0m     [38;5;28;01mimport[39;00m [38;5;21;01mtomli[39;00m [38;5;28;01mas[39;00m [38;5;21;01mtomllib[39;00m

[0;31mModuleNotFoundError[0m: No module named 'tomli'
ModuleNotFoundError: No module named 'tomli'

